version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /container/copa-extension
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: daily
