version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /backend
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /container/copa-extension
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
